# Generated by Django 5.1.6 on 2025-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_signed",
            field=models.BooleanField(default=False, verbose_name="Подписан ли"),
        ),
    ]
